# BlogFeedback Prediction - Using Regression

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [14]:
#Read training dataset
train = pd.read_csv("blogData_train.csv", header=None)
train.head(10)

,0,1,2,3,4,5,6,7,8,9,...,271,272,273,274,275,276,277,278,279,280
0,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.0
5,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.0
8,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0
9,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0

In [15]:
#Read test dataset
test = pd.read_csv("blogData_test-2012.03.31.01_00.csv", header=None)
test.head(10)

,0,1,2,3,4,5,6,7,8,9,...,271,272,273,274,275,276,277,278,279,280
0,6.004717,37.532440,0.0,347.0,0.0,2.603774,19.723646,0.0,223.0,0.0,...,0.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
1,7.777778,6.160407,1.0,18.0,6.0,3.333333,3.681787,0.0,13.0,2.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
2,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,34.589355,98.559500,0.0,713.0,2.0,14.205323,55.165180,0.0,596.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,65.469185,102.356910,0.0,724.0,20.0,24.737106,61.875816,0.0,586.0,2.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,10.630660,17.882992,1.0,259.0,5.0,4.018276,10.396790,0.0,235.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
7,4.410256,20.174519,0.0,129.0,0.0,2.602564,14.394033,0.0,117.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
9,122.812930,109.961100,0.0,1069.0,89.0,44.894543,74.547530,0.0,1046.0,12.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
#Divide training dataset in x and y
X_train = train.iloc[:,0:280]
y_train = train.iloc[:,-1]

In [17]:
#Build linear regression model
lin_model = LinearRegression()

In [18]:
#Train model on training dataset
lin_model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [19]:
#Predict using model

y_train_predict = lin_model.predict(X_train)

#Calculate mean squared error and root mean square error
mse = mean_squared_error(y_train, y_train_predict)
rmse = np.sqrt(mse)

print("The model performance for training dataset:\n")
print("MSE :", mse)
print("RMSE :",rmse)

The model performance for training dataset:

MSE : 903.1570149131361
RMSE : 30.05257085364139

In [20]:
#Divide test dataset in x and y
X_test = test.iloc[:,0:280]
y_test = test.iloc[:,-1]

In [21]:
#Predict target on test data using model

y_test_predict = lin_model.predict(X_test)

mse = mean_squared_error(y_test, y_test_predict)
rmse = np.sqrt(mse)

print("The model performance for testing dataset:\n")
print("MSE :", mse)
print("RMSE :",rmse)

The model performance for testing dataset:

MSE : 1632.1387433655323
RMSE : 40.399736921984186